version: "3.9"

services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ateo9
    networks:
      - controlimage_network

networks:
  controlimage_network:
    external: true
