services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "8082:8082"
    volumes:
      - image_uploads:/app/uploads
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ateo9
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.animal-adoption.com.br:8443/realms/ANIMAL_ADOPTION
    networks:
      - controlimage_network

volumes:
  image_uploads:

networks:
  controlimage_network:
    external: true
