services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ateo9
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_PASSWORD: 123ateo9
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.barbershop-app.shop:8443/realms/ANIMAL_ADOPTION
    networks:
      - controlimage_network

networks:
  controlimage_network:
    external: true
