version: "3.9"

services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://72.61.38.221:5432/animal_adoption
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123ateo9
      SPRING_DATA_REDIS_HOST: redis.barbershop-app.shop
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: 123ateo9
    networks:
      - bridge

networks:
  bridge:
    external: true
