spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.barbershop-app.shop:8443/realms/ANIMAL_ADOPTION
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/animal_adoption}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123ateo9}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: control_images
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${SCHEMA_NAME:control_images}
  data:
    redis:
      host: redis
      port: 6379
      password: "123ateo9"   # deixe vazio se n√£o configurou senha
      timeout: 2000ms
  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8082

upload:
  dir: uploads

keycloak-config:
  client-public-key: ANIMAL_ADOPTION_CLIENT
  internal-url: https://keycloak:8443